spring.datasource.url=jdbc:postgresql://dpg-da3cqi2bkg8c7389s5hg-a.virginia-postgres.render.com:5432/hapitaux
spring.datasource.username=brayano
spring.datasource.password=suvGKkwfwWQXU3qKxT4pe31FT4umFe2I

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.max-lifetime=280000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.validation-timeout=5000